spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
        ddl-auto: none
